### PR TITLE
Fix for font render bug

### PR DESCRIPTION
**Pull request by tylerburleigh**
Let's try this again :)

This is a fix for a bug with the feedback text in the test block on smaller screens, as shown below. Enclosing the feedback text in `<font size = 20></font>`  makes this text render correctly -- and consistent with the same feedback text in the practice block.

font-render

### CODE REVIEW

**Review by vsoch — COMMENTED** [review]
awesome! Is there any reason that you didn't just add a style tag with the correct font size attribute? I've never seen font as a div like that.

**Comment by tylerburleigh** [comment]
I agree, it is unusual. I formatted it this way to be conservative with the code changes. The other feedback text code is structured this way.

https://github.com/tylerburleigh/stroop/blob/c0b4bee3210b57f58d81ec2b8d7dede93304465d/experiment.js#L331

**Comment by vsoch** [comment]
Interesting! I don't think this is done anymore, but it looks like it's compatible with older browsers: 

https://kb.iu.edu/d/abai

I didn't write this code (an RA in my old lab did) but it must have been a decision based on this, so if it looks good to you, I'm happy to make the change :)

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
And a question for you - I haven't put thought into maintaining versions for experiments, but we probably should! What are your thoughts?

**Comment by tylerburleigh** [comment]
Yeah definitely, I think having multiple versions would be useful.

**Pull request merged**
